apiVersion: apps/v1
kind: Deployment
metadata:
  name: app42-deployment
spec:
  selector:
    matchLabels:
      app: app42
  replicas: 1
  template:
    metadata:
      labels:
        app: app42
    spec:
      containers:
      - name: app42
        image: wil42/playground:v2
---
kind: Service
apiVersion: v1
metadata:
  name: app42-service
spec:
  ports:
    - name: http
      port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: app42
  type: LoadBalancer
